version: "3.9"

services:
  backend:
    build:
      context: ./src/back
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: telemetry_user
      POSTGRES_PASSWORD: telemetry_pass
      POSTGRES_DB: telemetry_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  rabbitmq_data:
  postgres_data: